export const CodingStory = [
  "Hello world! I'm Luke Muehring - a coder, adventurer, and creative.",
  "Check out my blog for coding thoughts and trip reports on adventures!",
  "Here's what I've been working on recently.",
  "Let me tell you a little bit about myself.",
  "I’ve been writing code professionally for 4 years. I love working with the whole stack to craft a product. My frontend experience is in React and Angular, and my backend experience is in C#.",
  "After graduating from Georgia Tech in 2021, I moved to Seattle to work as a software engineer for Microsoft. Here, I practiced thorough code reviews, test driven development, and debugging complex systems while on call.",
  "At the same time, I was going to professional competitions for rock climbing. Climbing is a hobby-turned-passion that I started in high school. As I got better, I began to believe more and more in my potential as an athlete.",
  "After ten years of climbing, I made the US Team. I wondered how good I could get if I focused, especially with the 2024 Olympics around the corner.",
  "Juggling two professional careers at the same time would have been possible - I've balanced climbing with school, and managed to graduate (with full honors!). But to reach the level of athletic success I wanted, and to have a shot at the Olympics, I had to go all in. I took a hiatus from software engineering and moved to Salt Lake City, where the US Team trains.",
  "I focused entirely on preparing for elite climbing competitions - climbing sessions in the AM and PM, forearm-blasting 5.14 circuits, and hours teasing out arcane details of climbing technique. It was grueling but satisfying. I was chasing a dream I had always been curious about, and something I've always loved.",
  "During the hiatus, I experienced some interesting ups and downs. I fell short of qualifying for the Olympics, but I got to place top 3 at the US National Championships and ranked in the top 50 worldwide.",
  "After exploring competitions deeply, I felt that I satisfied my curiosity on professional climbing. I’m now applying the same lessons of grit and problem-solving to my software engineering career and adventure outdoors.",
  "Outside of work, I'm usually finding some way to move outside, and you can read about my adventures on my blog.",
  "If you have an idea to do something cool or want to talk, I’d love to get to know you better, so feel free to reach me using the email in the menu.",
  "Thanks for listening. I'm going to jump off a cliff now!",
];
