export const CodingStory = [
  "I'm Luke Muehring, a software engineer and former professional climber currently based in Salt Lake City.",
  "Check out the blog in the menu for my thoughts on coding and trip reports outside.",
  "Here's what I've been working on recently.",
  "Let me tell you a little bit about myself.",
  "I’ve been a full-stack engineer for 4 years, and a climber for 14.",
  "I enjoy being creative, which is why I graduated from Georgia Tech with a B.S. in Computational Media, created this website, and built a lot of my projects from scratch.",
  "After graduating in 2021, I moved to Seattle to work as a software engineer for Microsoft. It was a solid foundation for engineering: thorough code reviews, test driven development, and on-call shifts debugging complex systems.",
  "At the same time, I was competing in the professional open circuit for rock climbing. It's a hobby-turned-passion that I began in high school and haven't given up since. As I got better, I began to believe more and more in my potential as an athlete.",
  "Then, during my second year at Microsoft in 2023, I made the US Team after ten years of climbing. I wondered how good I could get if I focused, especially with the 2024 Olympics around the corner.",
  "Juggling two professional careers at the same time would have been possible - I've had to balance both climbing and academics from high school to Georgia Tech. But to reach the level of success I envisioned, and to have a shot at qualifying for the freaking Olympics, I had to go all in. I took a hiatus from software engineering and moved to Salt Lake City, where the US Team trains.",
  "I focused entirely on preparing for elite climbing competitions - AM and PM climbing sessions, 5.14 spraywall circuits, and hours teasing out subtleties of climbing technique. It was grueling but satisfying. I was chasing a dream I had always been curious about, and I got to do something I love.",
  "I experienced some interesting ups and downs. I fell short of qualifying for the Olympics, but I got to place top 3 at the US National Championships and ranked in the top 50 worldwide.",
"I explored competitive rock climbing deeply and reached a natural point of completion, and I’m now choosing to focus my energy on my software engineering career.",
  "I wanted to apply the discipline and problem-solving skills I developed as an athlete, so I created the website you're looking at, and another for a beach house rental business. Currently, I'm building full stack applications for Revere Health, Utah's largest physician group.",
  "Besides full-stack development, I'm interested in creative coding. I love working on this website, and I've got a few ideas for projects I'd like to realize (VisionOS app development, and an app that uses AI to help with journaling and categorizing thoughts).",
  "Doing fewer competitions has also given me more time to explore the outdoors, whether it's scrambling ridgelines, climbing granite, or skiing powder in the Wasatch. I recently got to do the WURL and want to do the Grand Teton Picnic next.",
  "If you have an idea to do something cool or want to talk, I’d love to get to know you better, so feel free to reach me using the email in the menu.",
  "Thanks for reading! I'm going to jump off a cliff now.",
];
