export const CodingStory = [
  "Welcome to my website! I'm a full-stack software engineer with over 3 years of experience based in Salt Lake City.",
  "If I'm talking too slowly, feel free to use the scroll wheel.",
  "Here's what I've been working on recently.",
  "Let me tell you a little bit about myself:",
  "For the past three years, I’ve been building full stack applications. I like to start with Figma to get out design ideas, and then implement the components with either React or Angular. For the backend, I've primarily worked with C# ASP.NET APIs and SQL for the data.",
  "I enjoy creatively designing and building a product across the full stack, which is why I graduated from Georgia Tech with a B.S. in Computational Media.",
  "After graduating, I moved to Seattle to work as a software engineer at Microsoft under the M365 organization.",
  "I worked at Microsoft for around two years - but in 2023, I made the US Team for competitive rock climbing. It was a hard decision, but I decided to give my professional athlete career a shot and focus entirely on my climbing.",
  "I moved to Salt Lake City, where the national team training center and strongest climbers in the US are located. During that year, I trained full-time for elite climbing competitions and explored my own interests with coding. I explored front-end design by creating RestAndRelaxVacation.com, and the website you're looking at.",
  "After placing in the top 3 at the US National Championships and ranking in the global top 50, I decided to continue my software engineering career with the discipline and problem-solving skills I developed as an athlete.",
  "Currently, I'm building full stack applications for Utah's largest physician group, Revere Health.",
  "Outside of work, I spend most of my time climbing, exploring Utah's epic mountains, and creating new things with code.",
  "Besides full-stack development, I'm interested in creative coding. I love working on this website, exploring VisionOS app development, and creating new designs for websites.",
  "Outside of my career, I still enjoy climbing but prefer to be in nature. It's pretty difficult for me to have a bad time outside. My current outdoor project is training for an alpine style WURL, a 36-mile ridgeline traverse with 18,000+ feet of elevation gain.",
  "If you have an idea to create something cool or just want to chat, I’d love to get to know you better, so feel free to reach me using the email in the menu.",
  "Thanks for getting to know me a little.",
];
